### ISSUE TITLE
It's need to install 2.5.0 version of protoc, otherwise mvn package will fail

### ISSUE THREAD

**Issue by ykgarfield** [Tencent/TubeMQ#1]
According to `docs\tubemq_user_guide.md`, if direct to execute `mvn clean package -Dmaven.test.skip`, it will report following error:

```
Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (default) on project tubemq-core: Cannot execute 'protoc'
```

So we need first to install `protobuf`, version is `2.5.0`, the project's protobuf-java version is 2.5.0, if installed version is not match 2.5.0, maybe be occur following error:

```
Protobuf installation version does not match Protobuf library version
```

The document is better to write this.

**Comment by tisonkun** [comment]
@ykgarfield thanks for reporting this! I think a prerequisite section is good to have under `docs/tubemq_user_guide.md`. Would you like to send a pull request?

**Comment by gosonzhang** [comment]
Thanks, we'll fix it.

**Comment by tisonkun** [comment]
Hi @gosonzhang, there is an ongoing pull request #2 to this issue. Could you please take a look at it?

**Comment by lujianyou** [comment]
> According to `docs\tubemq_user_guide.md`, if direct to execute `mvn clean package -Dmaven.test.skip`, it will report following error:
> 
> ```
> Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (default) on project tubemq-core: Cannot execute 'protoc'
> ```
> 
> So we need first to install `protobuf`, version is `2.5.0`, the project's protobuf-java version is 2.5.0, if installed version is not match 2.5.0, maybe be occur following error:
> 
> ```
> Protobuf installation version does not match Protobuf library version
> ```
> 
> The document is better to write this.

You are right,I have upgrade it to version 3.9.1,It works
