### ISSUE TITLE
RPC problem

### ISSUE THREAD

**Issue by aloyszhang** [Tencent/TubeMQ#101]
I found some confusing code in `NettyClient#call`.
```java
if (channel1 == null) {
            logger.error(new StringBuilder(256)
                    .append(this.addressInfo.getHostPortStr())
                    .append("'s channel is null").toString());
        } else {
            getChannel().write(pack);
        }
        if (callback == null) {
            try {
                return future.get(timeout, timeUnit);
            } catch (TimeoutException e) {
                requests.remove(request.getSerialNo());
                throw e;
            }
        } else {
            timeouts.put(request.getSerialNo(),
                    timer.newTimeout(new TimeoutTask(request.getSerialNo()), timeout, timeUnit));
        }
```
when channel is null, it'll continue run the following code. It seems meaningless since
client can't send request when channel is null.  I think maybe throw a `RuntimeExcetion` indicate channel is null is a better way.

Another problem here, currently, when send message asynchronously, it will build a `Timeout` after write data to channel. Since build a timeout may cause `RuntimeException`, it will trigger callback twice in this situaitons.

**Comment by aloyszhang** [comment]
@gosonzhang

**Comment by gosonzhang** [comment]
Thanks, @aloyszhang, can you contribute a PR to this question?
