### ISSUE TITLE
unseemly log print

### ISSUE THREAD

**Issue by aloyszhang** [Tencent/TubeMQ#109]
I found some code abount log printing like : 
```java
logger.debug(strBuffer
      .append("[Partition occupied], curr consumerId: ")
      .append(consumerId).append(", returned message : ")
      .append(responseB2C.getErrMsg()).toString());
```
I think it's not a good way to ouput log because code like  `responseB2C.getErrMsg()` will execute first even `logger`  level is above debug(INFO,WARN etc.)

**Comment by gosonzhang** [comment]
What do you mean: The current implementation will make strBuffer perform string concatenation first, even if the debug does not print, but will not achieve the goal of reducing CPU consumption.
Is there a similar introduction document for this question?

- - - - - - - - - - - -
你的意思是否为:  当前实现会使得即使debug不打印,strBuffer也会先进行字符串拼接,反而达不到减少CPU消耗的目标
这个问题有类似的介绍文档吗?

**Comment by aloyszhang** [comment]
Yes, detail information you can find in [SLF4JFAQ](http://www.slf4j.org/faq.html#logging_performance) and [BestPractices](https://wiki.opendaylight.org/view/BestPractices/Logging_Best_Practices)

**Comment by gosonzhang** [comment]
I will learn first, thank you very much!

**Comment by gosonzhang** [comment]
It's true, and there are problems in the section of the debug log print of TubeMQ, I will mention the PR modification, thank you! @aloyszhang
