### ISSUE TITLE
Does it support the AMQP protocol?

### ISSUE THREAD

**Issue by dbit-xia** [Tencent/TubeMQ#114]
Does it support the AMQP protocol?
can be applied to a variety of development languages.

**Comment by gosonzhang** [comment]
@dbit-xia ,thank you for your attention, TubeMQ does not support the AMQP protocol. It is based on the Topic-based Publish/Subscribe (P/S) model, it is similar to the Kafka interface and easy to using in big data scenarios. We accept other protocols or MQ clients through Proxy transit.

- - - - - - - - - - - - - -- - 
TubeMQ不支持AMQP协议。 它采用的是基于Topic的发布/订阅（P / S）模型，类似于Kafka接口，便于在大数据场景中使用。 我们通过代理传输接受其他协议或MQ客户端。
