### ISSUE TITLE
[PROPOSAL] TubeMQ Document Site 

### ISSUE THREAD

**Issue by tisonkun** [Tencent/TubeMQ#117]
**Motivation**

Currently TubeMQ project hosts its documentation under docs/ folder, which contains previously internal materials. This issue is towards adding a minimum viable prototype of the document site that hosts TubeMQ document and a formal structure to manipulate TubeMQ documents.

**Design**

Here is [the design document](https://docs.google.com/document/d/1Gmt9AOWDZm02MOZVQZCFHIzQzKuIwEFGr1_7UmKYbpE/edit?usp=sharing).

Basically we propose using [sphinx-doc](http://www.sphinx-doc.org/en/master/) as our document site build tool and [sphinx-intl](https://sphinx-intl.readthedocs.io/) as our i18n tool. The process of translation, i.e., i18n support follows [gettext](https://www.gnu.org/software/gettext/) working flow. Besides, we use GitHub Pages to server the site.

**(optional) Example snippet**

https://tencent.github.io/TubeMQ/en/html/user-guide.html

![image](https://user-images.githubusercontent.com/18818196/68548196-17ee0f80-0425-11ea-934d-9989d0f0aa11.png)

https://tencent.github.io/TubeMQ/zh/html/user-guide.html

![image](https://user-images.githubusercontent.com/18818196/68548205-2b997600-0425-11ea-9862-ab843f37cd30.png)

**Comment by ghost** [comment]
Sphinx require python toolset, I suggest one more lightweight document tools:

https://docsify.js.org/#/

It only render markdown as document, No need npm, no need install tools.
You can write a html page, then include a small javascript file, all things done. 
You can write markdown, the javascript will render it as document.
