### ISSUE TITLE
Webui page title display error

### ISSUE THREAD

**Issue by ykgarfield** [Tencent/TubeMQ#12]
The topic list、topic detail and other multiple pages title display error, as shown in the following figure:

![TIM截图20190917165505](https://user-images.githubusercontent.com/1425308/65026901-0714a680-d96c-11e9-8941-3d5dc741e2bb.png)

According to source code, tow places not set page title:

- `layout/default.vm`、`layout/tubeweb.vm` only judge two pages:

```
#if($page == "brokerList")
    #set($title="Broker列表")
#elseif($page == "brokerDetail")
    #set($title="Broker详情")
#end
```

-  `execute()` method of some `Action` implementation classes  not set `page` param, like `TopicDetail#execute()`:

```java
public void execute(RequestContext context) {
    // now, this method is empty, no following line code
    context.put("page", "topicDetail");
}
```

**Comment by gosonzhang** [comment]
see https://github.com/Tencent/TubeMQ/pull/22 and https://github.com/Tencent/TubeMQ/pull/28
