### ISSUE TITLE
Error when I use mvn compile

### ISSUE THREAD

**Issue by zehuaiWANG** [Tencent/TubeMQ#120]
Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (default) on project tubemq-core: Protobuf installation version does not match Protobuf library version

I think it should be a general protobuf. And it's better to use proboful 3.0.

**Comment by zehuaiWANG** [comment]
the same as issue #1

**Comment by gosonzhang** [comment]
Using 2.5.0 mainly is compatible with most business environments. If you can make a way to not configure the local environment, it is definitely the best. Can you contribute a PR?

**Comment by zehuaiWANG** [comment]
@gosonzhang @TisonKun It seems that tison has fixed the issue in pr #121, I has verified it and it looks well in my pc.  Thank you all~

**Comment by gosonzhang** [comment]
I found a problem: tubemq-core compilation because this modification needs to compile for 10 minutes, this is not very good for users, and network exceptions can easily lead to project compilation failure.

**Comment by zehuaiWANG** [comment]
Do you mean that auto downloading will lead to the increase of compilation time? Yes, but he doesn't mean that there will be errors. In my opinion, compilation failure due to network problems is inevitable, but problems caused by version conflicts will make users more confused. I think it can be explained in the document that this compilation needs a good network environment and provides a way for users to download protobuf independently. (although protobuf version 2.5 is no longer available). @gosonzhang

**Comment by gosonzhang** [comment]
Can there be a good way to solve this problem? Users can download the specified version of protobuf through configuration, or get the dependent package directly from the local without downloading?
The main problem of protobuf is to be compatible with the internal system

- - - - - - - - - - - - - - - - - - -
能否有一個好的方法來解決這個問題,用戶可以通過配置,允許通過網絡下載指定版本的protobuf,或者不用下載,直接從本地獲取該依賴包?

protobuf版本的問題,主要是兼容内部系統需要

**Comment by tisonkun** [comment]
@gosonzhang you are able to use local `protoc` executable as described [here](https://www.xolstice.org/protobuf-maven-plugin/usage.html)

![image](https://user-images.githubusercontent.com/18818196/68680187-332f5b00-059c-11ea-9151-ba765fc61470.png)

**Comment by tisonkun** [comment]
And I think it is only require downloading at the very first time.

---

第一次执行 mvn install 之后本地就有对应的 protoc exe 了，不是每次编译都需要下载。使用本地的 exe 的方法见上。

**Comment by gosonzhang** [comment]
Thanks @TisonKun , I'll check again to see if there are any other questions

**Comment by tisonkun** [comment]
closed as development moved to https://github.com/apache/incubator-inlong/
