### ISSUE TITLE
Broker is slower than the consumer's VisitAuthorizedToken update，the consumer will continue to warn the failure of certificate.

### ISSUE THREAD

**Issue by Libeibei1990** [Tencent/TubeMQ#125]
If broker is slower than the consumer's VisitAuthorizedToken update，the consumer will continue to warn the failure of certificate.

[BaseMessageConsumer]  [heart2broker error] certificate failure, BrokerID:BrokerIP:BrokerPort's partitions ared released, Visit Authorized Token is invalid!

**Comment by gosonzhang** [comment]
This happens when the client pulls the visitToken faster than the broker, I will mention a PR to modify the problem.

thanks
