### ISSUE TITLE
Adjust version of TubeMQ

### ISSUE THREAD

**Issue by tisonkun** [Tencent/TubeMQ#13]
https://github.com/Tencent/TubeMQ/blob/bd1f48c496e5fd4ddb880703eb0f1d3c7818d131/pom.xml#L26

Start with a new iteration looks reasonable. What do you think @gosonzhang @yiheng ?

**Comment by yiheng** [comment]
Yeah. Also, use snapshot version on master may be more reasonable.

**Comment by tisonkun** [comment]
I think this issue has been addressed by 84a056a843fbb8e586d36f3b0876f6cf33062053
