### ISSUE TITLE
com.tencent.tubemq.corebase.protobuf.generated.ClientMaster

### ISSUE THREAD

**Issue by wangyughost** [Tencent/TubeMQ#135]
这个是什么类？ 项目里面没有无法编译，怎么解决

**Comment by wangyughost** [comment]
com.tencent.tubemq.corebase.protobuf.generated.ClientMaster
这个是什么类？ 项目里面没有无法编译，怎么解决

**Comment by gosonzhang** [comment]
Need to do PB compilation,  please refer to the compiled documentation in docs

**Comment by gosonzhang** [comment]
see https://github.com/Tencent/TubeMQ/blob/master/docs/tubemq_user_guide.md or https://github.com/Tencent/TubeMQ/blob/master/docs/tubemq_user_guide_cn.doc

I'll close issue @wangyughost .
