### ISSUE TITLE
Shielding abnormal broker should not be limited to IOException, any exception in the writing process should be managed.

### ISSUE THREAD

**Issue by Libeibei1990** [Tencent/TubeMQ#137]
Shielding abnormal broker should not be limited to IOException, any exception in the writing process should be managed.
For example, modify writing path permission which will affect data writing directly.

[https://github.com/Tencent/TubeMQ/blob/master/tubemq-server/src/main/java/com/tencent/tubemq/server/broker/msgstore/disk/MsgFileStore.java](url)

catch (**final IOException e**) {
            ServiceStatusHolder.addWriteIOErrCnt();
            logger.error("[File Store] Append message in file failed ", e);
            throw e;
}

**Comment by gosonzhang** [comment]
Thanks, I'll check it and fix it.
