### ISSUE TITLE
If the broker was blocked, it can't be restored to the disabled state after restarting the master.

### ISSUE THREAD

**Issue by Libeibei1990** [Tencent/TubeMQ#145]

**Comment by gosonzhang** [comment]
Thanks，I‘ll check it

**Comment by gosonzhang** [comment]
Master encountered some problems while processing Broker's disk IO exception report: if Master restarts and memory data is lost, related information will be lost and will not be recovered; then, if the number of failed Brokers exceeds the number allowed by the blocking policy , They will not be blocked all, but unblocked Brokers do not mean that there are no exceptions, these Brokers should be queried in some places

I will solve these problems, thanks

- - - - - - - - - 
分析了下，Master在处理Broker上报磁盘IO异常时存在一些问题：如果Master重启，内存数据丢失时，相关的信息就丢失没有恢复；然后，如果故障Broker个数多于屏蔽策略允许个数时，多出部分将不会被屏蔽，但不屏蔽不表示没有异常，应该有地方来查询这批Broker

我将修复这些问题，谢谢
