### ISSUE TITLE
Inconsistency in the default conf and docs

### ISSUE THREAD

**Issue by dongxuwang** [Tencent/TubeMQ#147]
**Problem description**

It'd be better to keep the consistency of the default conf and docs, take webPort for example:

In conf/master.ini | In tubemq_user_guide.md
------------------|------------------------
8080 | 8088

**(optional) Reproducer snippet**

**(optional) Suggestions for an improvement**

Make both the default conf and user_guide consistent.

**Comment by gosonzhang** [comment]
Yes, it is Inconsistency in the default conf and docs. This problem is what you found, and can you mention a PR modification and let this system record your discovery and contribution?
- - - - - 
是的，确实不一致。你发现了这个问题，所以能否提一个PR修改下，让这个系统留下你的发现和贡献？
