### ISSUE TITLE
tubemq-server module should remove the dependency of tubemq-example module

### ISSUE THREAD

**Issue by ykgarfield** [Tencent/TubeMQ#18]
Now, the `tubemq-server` module depend on `tubemq-example` module, as shown of `tubemq-server` pom.xml:

```xml
<dependency>
    <groupId>com.tencent.tubemq</groupId>
    <artifactId>tubemq-example</artifactId>
</dependency>
```

In theory, `tubemq-server` should not depend on `tubemq-example`.

**Comment by tisonkun** [comment]
Hi @ykgarfield I think you're right. Is there any existing dependencies from `tubemq-server` to `tubemq-example`? If not, we can directly remove this code snippet; if so, maybe it is worth separated issues to resolve the unreasonable dependencies respectively.

**Comment by ykgarfield** [comment]
I check the code,  no dependencies from `tubemq-server` to `tubemq-example`, also I remove the dependency and run in IDE, it's no problem.

**Comment by tisonkun** [comment]
Thanks for your investigation. It would be nice if you open a pull request to this issue  :-)
