### ISSUE TITLE
Remove outdated dependency jackson-mapper-asl

### ISSUE THREAD

**Issue by quaff** [Tencent/TubeMQ#20]
Please reuse `fastjson` or upgrade to latest `jackson-databind`.

**Comment by quaff** [comment]
I've created #21

**Comment by gosonzhang** [comment]
Very meticulous discovery, thank you!

－－－－－－－－－－

非常细致的发现，谢谢！

**Comment by quaff** [comment]
还有很多依赖过时了

**Comment by gosonzhang** [comment]
Yes, you are right, online system, we will not easily upgrade dependent components based on the stability of the system. The next component to be upgraded is netty, ready to upgrade to 4.X to improve system performance.

－－－－－－－－－－－－－－－－－－－－－

是的，你说的对，线上系统，我们会基于保证系统的稳定性考虑不轻易升级依赖组件．接下来有计划升级的组件是netty，准备升级到 4.X，以提升系统性能
