### ISSUE TITLE
flink-connector-TubeMQ

### ISSUE THREAD

**Issue by pierre94** [Tencent/TubeMQ#24]
hope TubeMQ can provide flink-connector？

**Comment by tisonkun** [comment]
Hi @pierre94 thanks for creating this issue! 

We have already had experiences connecting TubeMQ with Apache Flink. And it is in our roadmap to provide a flink-connector-tubemq!

**Comment by liangyuanpeng** [comment]
@TisonKun 
Sounds great ! I'm looking forward to it !

**Comment by tisonkun** [comment]
Closed as development moved to [Apache InLong (Incubating)](https://github.com/apache/incubator-inlong) already.
