### ISSUE TITLE
用户文档里：关于集群有俩个角色：master ,broker的疑问

### ISSUE THREAD

**Issue by GodBlessWorld** [Tencent/TubeMQ#27]

**Comment by GodBlessWorld** [comment]
在看用户文档时，原文：There're two roles in the cluster: Master and Broker. 乍看时有点费解，这俩个角色不应该是master和slave嘛？broker应该是master跟slave的统称呀。难道tubeMq跟世界公认的消息中间件基本术语不一样？

**Comment by gosonzhang** [comment]
You are right, the cluster's control role is called controller, or manager, it will be more suitable than the master, the system is called by the original personnel, and later the name will follow the name unchanged.

Now the requirements for external open source are different. If the name is not significant, we will adjust it in later versions. Then, when other components on the chain are open source, we will strictly align them to avoid unnecessary learning costs for everyone. .

Thank you!
－－－－－－－－－－－－－－－－－－－

你说的对，集群的管控角色叫controller，或者manager，会比master更合适些，系统最初人员这么称呼，后来者也就把这个名字沿袭下来没有变动．

现在对外开源了要求也不同，这个名字如果影响不大的话我们会在后面版本进行调整，然后，后续这个链条上其他的组件开源时，我们会严格的对齐，避免给大家产生不必要的学习成本．

谢谢！
