### ISSUE TITLE
源码中找不到类

### ISSUE THREAD

**Issue by wwjjqq** [Tencent/TubeMQ#36]
com.tencent.tubemq.corebase.protobuf.generated.ClientBroker这个类找不到，麻烦解决下

**Comment by klboke** [comment]
编译下tubema-cor模块就有了，你需要搭建下protobuf编译环境：https://github.com/protocolbuffers/protobuf/releases/tag/v2.5.0

**Comment by tisonkun** [comment]
duplicated #7
