### ISSUE TITLE
Configuration file should not contain Chinese

### ISSUE THREAD

**Issue by tisonkun** [Tencent/TubeMQ#39]
**Problem description**

https://github.com/Tencent/TubeMQ/blob/master/conf/broker.ini
https://github.com/Tencent/TubeMQ/blob/master/conf/master.ini

**(optional) Suggestions for an improvement**

better to translate Chinese comments to English.

**Comment by gosonzhang** [comment]
see https://github.com/Tencent/TubeMQ/pull/43
