### ISSUE TITLE
编译期间遇到两个问题

### ISSUE THREAD

**Issue by TeddiWolf** [Tencent/TubeMQ#42]
1，protobuf必须是2.5.0，其它都不行。2，com.sleepycat.je中需要自己加个版本号才OK

**Comment by tisonkun** [comment]
1. protobuf 2.5.0 is a prerequisite documented [here](https://github.com/Tencent/TubeMQ/blob/master/docs/tubemq_user_guide.md#prerequisites)

2. could you please share the error log?
