### ISSUE TITLE
Build all modules with the same jdk version

### ISSUE THREAD

**Issue by guangxuCheng** [Tencent/TubeMQ#44]
![image](https://user-images.githubusercontent.com/16833559/65416289-1b541a00-de2a-11e9-9e3b-cd2b1c5c9dd0.png)

Currently tubemq-server is built with JDK 8, but other module is built with JDK 7.

Maybe we should use the same JDK version for all modules.

If so, which one to use?

**Comment by gosonzhang** [comment]
The client is based on 1.7 to avoid the business environment, java is not a high version, the server depends on the BDB requires 1.8 version of java

- - - - - - - - - - - - - - - - - - - - -  - - - - - - - - 

客户端基于1.7避免业务环境的java不是高版本情况，服务端依赖的BDB要求1.8版本的java
