### ISSUE TITLE
How to config more than one master?

### ISSUE THREAD

**Issue by TeddiWolf** [Tencent/TubeMQ#49]
How to config serveral master?  I didn't find anywhere mention it.

**Comment by gosonzhang** [comment]
This part has been removed and I will provide it to you tomorrow.

- - - - - -  - 
该部分内容被去掉了,明天我提供给你

**Comment by gosonzhang** [comment]
see https://github.com/Tencent/TubeMQ/blob/master/docs/tubemq_user_guide_cn.doc
