### ISSUE TITLE
文档什么时候完善？

### ISSUE THREAD

**Issue by xiaoya0991** [Tencent/TubeMQ#5]
安装文档时候完善

**Comment by tisonkun** [comment]
@xiaoya0991 你好，请问你在阅读安装文档的时候发现了什么具体的不完善之处呢？

同时 #2 是一个正在 review 中的 pull request，介绍了安装过程中要求预先装好 protobuf 工具的文本。如果你还发现了其他问题，欢迎详细描述或者开启一个 pull request 修复。

**Comment by honestAnt** [comment]
有文档，只是不太友好吧

**Comment by gosonzhang** [comment]
We will gradually improve the documentation, if there are any imperfections or missing places, welcome to contribute.

- - - - 

我们会逐步完善文档，如果有不完善或者缺失的地方，欢迎贡献.
