### ISSUE TITLE
Improvement the exception type of MasterConfig throws

### ISSUE THREAD

**Issue by ykgarfield** [Tencent/TubeMQ#50]
**Motivation**
`MasterConfig`  load configs of  `master.ini`, parse and check.If has problems, almost of them throws `NullPointerException` or `IllegalArgumentException`.But in some cases, throw `NullPointerException` probably inappropriate.For example:

- code snippet 1:

```java
try {
	this.hostName = masterConf.get("hostName").trim();
	AddressUtils.validLocalIp(this.hostName);
} catch (Throwable e) {
	throw new NullPointerException(new StringBuilder(256)
			.append("Illegal hostName value in ").append(SECT_TOKEN_MASTER)
			.append(" section!").toString());
}
```

- code snippet 2:
```java
if (!this.startConsumeAuthenticate && this.startConsumeAuthorize) {
	throw new NullPointerException(
			"startConsumeAuthenticate must set true if startConsumeAuthorize is true!");
}
```

`IllegalArgumentException` may more reasonable or use cusutom exception(for example: `ConfigException`).

In addition, the following exception message not clear enough:

```java
String tmpAuthToken = masterConf.get("confModAuthToken").trim();
if (tmpAuthToken.length() > TServerConstants.CFG_MODAUTHTOKEN_MAX_LENGTH) {
	throw new IllegalArgumentException(
			"Invalid value: confModAuthToken's value > " + TServerConstants.CFG_MODAUTHTOKEN_MAX_LENGTH);
}
```

Here is the string  length illegal, the more detail exception message should be:

```
"Invalid value: the length of confModAuthToken's value > " + TServerConstants.CFG_MODAUTHTOKEN_MAX_LENGTH);
```

**(optional) Design**

**(optional) Example snippet**

**Comment by gosonzhang** [comment]
@ykgarfield, this is a question. Can you contribute a PR?

**Comment by gosonzhang** [comment]
see https://github.com/Tencent/TubeMQ/pull/53

**Comment by gosonzhang** [comment]
Thanks @ykgarfield
