### ISSUE TITLE
性能方面有没有压测数据提供参考。

### ISSUE THREAD

**Issue by hxnan** [Tencent/TubeMQ#6]
性能方面有没有压测数据提供参考。
比如日均接入量超过 25 万亿条，每秒 86400条，使用了多少服务器资源？

**Comment by hiSolitude** [comment]
同问

**Comment by hxnan** [comment]
> 同问

https://github.com/Tencent/TubeMQ/blob/master/docs/tubemq_perf_test_vs_Kafka_cn.md
