### ISSUE TITLE
com.tencent.tubemq.server.master.TMaster  报错

### ISSUE THREAD

**Issue by hanwei-mtsm** [Tencent/TubeMQ#7]
import com.tencent.tubemq.corebase.protobuf.generated.ClientMaster.*;
报错。源文件缺失protobuf包。

**Comment by gosonzhang** [comment]
It needs to be compiled before use
------------------------------------------
工程下载下来要先编译

**Comment by tisonkun** [comment]
@hanwei-mtsm Hi, please note that the import has a package contains `protobuf.generated` that infers it is generated by protobuf. Generally you need to build the project first for globally indexing the source code.

---

你好，包名包括了 `protobuf.generated` 字段，通常这意味着这份代码由 protobuf 生成。你可以阅读 protobuf 的[官网资料](https://developers.google.com/protocol-buffers/)了解更多关于代码生成的信息，但一般来说，你需要先 build 整个工程以生成相关的源代码文件。在 build 之后你的 IDE 例如 IDEA 应该就能正确索引代码了。
