### ISSUE TITLE
Improvement `BdbGroupAdmin` class

### ISSUE THREAD

**Issue by aloyszhang** [Tencent/TubeMQ#78]
`BdbGroupAdmin`  is used to remove node in replication group.
Currently, `BdbGroupAdmin` does't handle the exception and missing the necessary message about the remove process. I think we should:

1. print the node information before and after remove node
2. catch and handler the exception separately, then print some readable information

What do you think @gosonzhang ?

**Comment by gosonzhang** [comment]
Very good advice, can you contribute a PR?

**Comment by aloyszhang** [comment]
@gosonzhang I have open a PR[ here](https://github.com/Tencent/TubeMQ/pull/79)
