### ISSUE TITLE
Useless `main` method in subclass of Action

### ISSUE THREAD

**Issue by aloyszhang** [Tencent/TubeMQ#84]
I found some `main` method just sleep 100000000ms in a new thread in some subClass of `Action`, 
```
public static void main(String[] args) {
        new Thread() {
            @Override
            public void run() {
                try {
                    Thread.sleep(100000000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }.start();
    }
``` 
It seems useless. and I think wo can remove these code. What do think about it ?
 @gosonzhang

**Comment by tisonkun** [comment]
Make sense to me. Also I'm curious the history why we introduce such code snippets.

**Comment by gosonzhang** [comment]
This should be used for unit testing a long time ago, not removed.

Can you fix it？

**Comment by aloyszhang** [comment]
@gosonzhang ok, I'll contribute a PR.

**Comment by gosonzhang** [comment]
thanks
