### ISSUE TITLE
Downgrade minimum jdk version to jdk7

### ISSUE THREAD

**Issue by tisonkun** [Tencent/TubeMQ#97]
ref #73 

After an investigation we notice that je 7.3.7 doesn't require jdk8 so that for being compatible with jdk7 I propose

1. configure maven-compiler-plugin in tubemq-server using jdk7
2. downgrade travis environment to use openjdk7
3. correspondingly update documentation

**Comment by gosonzhang** [comment]
LGTM +1

**Comment by tisonkun** [comment]
The documentation already mentions "Java 7 or Java 8", I think it correctly reflects our requirement.

Close this issue as resolved.
